### ISSUE TITLE
Wrap post categories in an ! if function exists check

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#1]
`vantage_get_post_categories` should ideally be wrapped in an `if( !function_exists` check to make child theme adjustments easier.

https://github.com/siteorigin/vantage/blob/develop/inc/template-tags.php#L333

**Comment by gregpriday** [comment]
@adiraomj this is quite a big one. Reckon you could take a look?

**Comment by adiraomj** [comment]
@gregpriday havn't you addressed this issue with this [commit](https://github.com/siteorigin/vantage/commit/593b08d994d5b29de3b95e6b5d5c557e336bda0b)?

**Comment by gregpriday** [comment]
Aaaah yeah, thought @misplon said there were other functions missing this
check. Maybe just do a quick check through of all the functions and see if
there are any other ones we can wrap.

**Comment by Misplon** [comment]
@gregpriday @adiraomj This looks awesome, thanks G.

**Comment by adiraomj** [comment]
@Misplon this issue still needs some work. I will send a PR later today.

**Comment by Misplon** [comment]
@adiraomj Sorry man, thanks for picking this up. Chat later.
