### ISSUE TITLE
Add Email icon to social widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#10]
You should be able to set an email widget. It might be nice if this icon was "smart" in that it would check if it was an email and set it as a mailto if it was.

![sample](https://cloud.githubusercontent.com/assets/17275120/13674198/576f3904-e728-11e5-9e1a-4a4eba95a2c3.png)

**Comment by Misplon** [comment]
@adiraomj When we hit this, let's check that the Vantage Social Icon widget has access to all the latest Font Awesome social icons. Thanks man.

**Comment by adiraomj** [comment]
Will do @Misplon :-)

**Comment by Misplon** [comment]
Should we link the mail icon to a `mailto` link?

I'm keen for a phone icon using the [tel](https://developers.google.com/web/fundamentals/native-hardware/click-to-call/?hl=en) link format. @gregpriday you cool with this?

**Comment by AlexGStapleton** [comment]
I don't think hardcoding the link with a mailto is a good idea. I may wish to link to my contact page rather than directly receive emails.

It would, however, be a good idea to check for an email and then apply the mailto: to the link if not already present.

**Comment by gregpriday** [comment]
Telephone icon would be a really nice addition. I also agree with @AlexGStapleton - ideally, we'd have some sort of smart detection for email addresses. Just as a failsafe for users who forget to add it in.

**Comment by Misplon** [comment]
Awesome guys. Should we do the same for the tel link? For the tel link format to dial correctly it needs the full international number so that does add a level of complexity.

**Comment by gregpriday** [comment]
Yeah, I think so. Some basic phone number detection should do the trick. It mainly needs to detect that what's entered isn't a valid URL.

**Comment by adiraomj** [comment]
Should we also move the RSS link to the end? Maybe before the email and phone links? Seems a little out of place in between all the social links.

**Comment by gregpriday** [comment]
Yeah, I think moving it to the end would be a good idea.

**Comment by adiraomj** [comment]
What  background colors would you suggest for the mail and phone links?

**Comment by AlexGStapleton** [comment]
The phone links should be either green (iOS) or blue (Skype is a blue background with a white icon. Android is blue icon with a transparent background) IMO.

**Comment by AlexGStapleton** [comment]
Actually, scratch that. Just mimic iOS imo.

Green = phone
Blue = mail

**Comment by adiraomj** [comment]
ok..
