### ISSUE TITLE
Logo in Menu: Vertical padding alignment issue

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#107]
When Logo in Menu is in use and users enter a vertical menu padding that's greater or less than the height of the logo, you get alignment issues as follows:

![2](https://cloud.githubusercontent.com/assets/789159/16045717/01b142d8-324a-11e6-89d5-79e41ddd505a.png)

The issue is that the menu item vertical padding is applied as follows:

`.main-navigation ul li a, #masthead.masthead-logo-in-menu .logo`

What we should consider doing is removing `#masthead.masthead-logo-in-menu .logo` from this Customizer setting. That means that `#masthead.masthead-logo-in-menu .logo` will only have `25` right and left padding but no top and bottom padding. 

Next, we'd remove the `.logo` `float: left` and instead use `display: inline-block` for both the logo and the menu. This would allow us to use `vertical-align: middle` for the logo. The end result is that the logo will vertically align middle in the given space which is set by the menu padding. 

There might be some Custom CSS knock on issues but it would solve this header alignment issue for a lot users. Not sure how much @AlexGStapleton has been dealing with this recently but in the past I helped lots of users solve this with Custom CSS.

@adiraomj Might have other ideas on how to best implement this.

**Comment by AlexGStapleton** [comment]
Can confirm, this is a common support request.
