### ISSUE TITLE
Disabled responsive layout and mobile menu

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#109]
When the Responsive Layout is unchecked, the mobile menu still shows. This should be not be the case.

What do you guys think?

**Comment by Misplon** [comment]
I don't think it should. @gregpriday ?

**Comment by adiraomj** [comment]
Unchecking `Responsive Layout` only works for `Boxed` layout. If you choose `Full Width` layout, it does not seem to work very well. @Misplon can you please confirm. Thanks.

**Comment by Misplon** [comment]
@adiraomj At the moment Vantage just replaces the normal viewport with the following: `<meta name="viewport" content="width=1280">`. Responsive behaviour will be disabled for mobile users but not for browser resizing on desktop. It doesn't use the more exhaustive method of prefixing responsive classes with a body class or similar method. 

How did you do it for North? With a CSS class prefix or different method?

**Comment by adiraomj** [comment]
In north we added the class `responsive` to the body. When the responsive layout is disabled the main container is set to a fixed width.

**Comment by Misplon** [comment]
@adiraomj I think it would be fine to use the same method in Vantage as you did with North if you're happy with that.

**Comment by adiraomj** [comment]
Yes. I'll do that then. I was just thinking that such features should work in a similar manner across all our themes :)

**Comment by Misplon** [comment]
Greg and I have been loosely discussing a starter theme. We had one in the past but didn't pursue it much. We're keen to get one started again. So yes, we're with you, no point in reinventing the wheel each time. It'll be much easier to have these standard features the same across themes.
