### ISSUE TITLE
Custom Menu Widget should have styling in the footer

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#11]
The custom menu widget has theme styling when in the header widget area but not in the footer widget area.

**Comment by gregpriday** [comment]
Agreed. We just need to figure out what sort of styling to use. Maybe we need to have this designed.

**Comment by Misplon** [comment]
When we get to this, let's pick a vertical menu style or ask Ricardo if he can mock something up for us.

**Comment by AlexGStapleton** [comment]
Yeah that could be a cool idea.

**Comment by Misplon** [comment]
@adiraomj would you like to take this on? We could perhaps keep it simple. Remove the list style, remove the list left padding and add an indented line below each item, much like the mobile menu in Vantage. We could tie the line indentation color to the footer background color setting.
