### ISSUE TITLE
Complete Navigation settings defaults

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#113]
Theme Settings > Navigation appears to be missing a few defaults.

**Comment by adiraomj** [comment]
@Misplon seems like all the defaults have been set.

Ref: https://github.com/siteorigin/vantage/blob/develop/inc/settings.php#L289-L300

Which field is giving you problem?

**Comment by Misplon** [comment]
Must have been looking at another branch. That looks perfect. Thanks dude.
