### ISSUE TITLE
Custom Menu In Footer: Add Drop Down Support or indication of different level

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#114]
Currently (in the latest dev version), the custom menu widget in the footer doesn't support drop down menus nor does it provide a visual indication of an item being a child.

This might mislead certain people into thinking this is a bug as they would either expect a drop down or at the very least an indication of a different level.

Reference Screenshots:
![](https://i.imgur.com/PJ129NN.png)
![](https://i.imgur.com/vz43oBk.png)

**Comment by AlexGStapleton** [comment]
In the current (release) version of Vantage the menu appears like so:

![](https://i.imgur.com/s1z3bs6.png)

**Comment by adiraomj** [comment]
This was done with #112. @Misplon what do you think?

**Comment by Misplon** [comment]
@AlexGStapleton Not sure you have a full cache refresh there. Should be looking like this:

<img width="614" alt="menu" src="https://cloud.githubusercontent.com/assets/789159/16335147/62deb28a-3a05-11e6-9e80-3979abe63fa1.png">

@adiraomj I think if we add some left margin for sub-menu items it should be a good enough indicator for child/drop-down items.

**Comment by AlexGStapleton** [comment]
@Misplon That image matches my reference screenshot (as below). I just don't have the widget title pictured in the image and I've cropped (read: via [ShareX](https://getsharex.com/)) it to lower the width of the image.

![](https://i.imgur.com/vz43oBk.png)

**Comment by adiraomj** [comment]
Does this look better
![footer-menu-indent](https://cloud.githubusercontent.com/assets/3372029/16338421/36ac6556-3a3a-11e6-964e-2a6c2a6e8250.png)

**Comment by AlexGStapleton** [comment]
Just to clarify, the bolding is from something else, right?

**Comment by adiraomj** [comment]
Guess so. The only thing I have changed is the `margin-left` for `.sub-menu`.

**Comment by Misplon** [comment]
Looking good
