### ISSUE TITLE
Masthead Layout template suggestion: Widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#116]
I've had a few people in the past ask for this in the past (at least a dozen premium users - either directly or indirectly) but it would be a good idea to add a masthead layout option that replaced the entire header with a full-width widget area. This will allow the user to place a layout builder widget there and build their desired header. This in turn will allow the user to create a non-standard header without help from support.

The navigation should still be present until the user specifically sets the Masthead Menu template to blank.

**Comment by adiraomj** [comment]
Shall I go ahead with this?

**Comment by gregpriday** [comment]
I've always been keen on adding this. @adiraomj - if you're keen to take it on, then definitely go ahead.

**Comment by Misplon** [comment]
My thoughts with the mobile menu would be to check that it works nicely when a custom menu widget is added. If a user wants a menu and a mobile menu they'd add a custom menu widget. We'd need to check that styling and the breakpoint setting still works.

**Comment by adiraomj** [comment]
@Misplon Rather that touch the navigation bar, we can let users enable/disable it using existing settings. We can then check for widgets in the new widget section and apply it to both layouts. I'll send a PR. Please have a look and let me know what you think. :)
