### ISSUE TITLE
Post Author Box: Add "Text to display when author's bio is empty"

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#122]
If the authors bio is empty, a blank space is output. This looks odd and there maybe should be setting to control what is displayed instead.

![](https://i.imgur.com/kAQCl86.png)

**Comment by Misplon** [comment]
@AlexGStapleton I'm not sure this warrants adding another setting. Each new setting has an overhead so we need to be as careful as possible with additions. I'm with you that there is a lot of negative space with no bio is added but hopefully, the workflow is like this:

Enable author bio.
Check single post.
See the bio box is blank.
Go to Users and add a bio.

**Comment by gregpriday** [comment]
We can always check access rights. If the user has access rights to edit the user, then it could display a link saying "Click here to enter a user bio". Something like that.

**Comment by Misplon** [comment]
@adiraomj Let's implement as suggested. Nice functional addition, dig it. Thanks.
