### ISSUE TITLE
UX Post Author's Comments Customizer: Supports HTML initally customizer but on reload HTML is removed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#123]
The Post Author's Comments field in the customzier will allow HTML initially but the HTML is stripped on save. This is slightly misleading as the formatting works as expected when adding it.

I think if you're not going to support HTML (which I think basic formatting should be supported), you should strip it from the customizer as to not confuse people.

**Comment by Misplon** [comment]
@adiraomj Please, can we have a look at Post Author's Comments field in the Customizer with `wp_kses_allowed_html` or other suitable function. Thanks :)
