### ISSUE TITLE
Add Menu Font Setting

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#124]
This is a semi-frequent support request but basically users would like the ability to set a custom font for the menu that is separate to all font settings.

**Comment by Misplon** [comment]
@adiraomj Please, proceed with this addition when possible. Thanks.

**Comment by adiraomj** [comment]
@AlexGStapleton which elements should the font be applied for? Is it the menu items only. Or do we also include the [menu text](https://github.com/siteorigin/vantage/blob/develop/inc/settings.php#L107-L109)?

**Comment by AlexGStapleton** [comment]
I'm not too sure. @Misplon thoughts?

**Comment by Misplon** [comment]
@adiraomj Menu items/links and menu text should be good. Thanks.
