### ISSUE TITLE
Mobile Menu item borders should have a setting to adjust the colors.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#126]
You're able to adjust the Menu borders but not the menu item borders. This seems odd as certain combinations of menu backgrounds and menu text would look better if the menu item borders color could were also adjusted.

**Comment by Misplon** [comment]
@AlexGStapleton Have there been any requests for this? The mobile menu style section has a lot of settings already. If this has been requested a few times or not yet then I'd suggest we leave it for the mean time.

**Comment by AlexGStapleton** [comment]
As these settings aren't in the love version I've only had indirect requests so I'm happy with waiting for feedback on this one.

**Comment by Misplon** [comment]
Sweet, let's see how it goes.
