### ISSUE TITLE
Add comment specific theme design settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#129]
In relation to #128 you should be able to specifically adjust the colors of this section and these settings should be stored in their own settings group.

I think you should be able to:
- Set generic comment color (date, name, etc)
- Adjust the comment headers (Comment tally and Leave a reply)
 - Set a reply background
- Adjust the author tag text and background color

**Comment by Misplon** [comment]
@AlexGStapleton We ideally need to make as many decisions for the user as possible. The more color settings we add the greater the overhead of maintenance, it's also much harder for users without a keen design eye to get color combinations correct when a lot of options are presented. At this stage, I'd suggest we tie color settings to existing color options as much as possible.

**Comment by AlexGStapleton** [comment]
Ah okay, yeah that makes sense.

**Comment by Misplon** [comment]
Cool, let's see how we do in the other case logged.
