### ISSUE TITLE
Add ability to adjust button gradients

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#130]
Currently you're stuck with the default gradient buttons for certain form elements (comment section) and navigation elements. This would be fine but as you can easily adjust other theme colors you should be able to adjust the button gradients also.

![](https://i.imgur.com/AgnGJHx.png)
![](https://i.imgur.com/XXBRMvx.png)

**Comment by adiraomj** [comment]
To implement this I was thinking we can add a new section called **Buttons** under theme design. Two settings we can start with are _Button Color_ and _Remove Button Gradient_. Any suggestions?

**Comment by Misplon** [comment]
@adiraomj Sounds good. How do you want to do this? Do you want to create a gradient from the color chosen? What about the border color? Do you want to just use a darken function for that or offer it up as a setting? If we're doing this we should consider an option to remove the shadow.

**Comment by adiraomj** [comment]
@Misplon In addition to Button Color and Remove Button Gradient that I mentioned above, I will add options for the Border Color and removing of the shadow. I'll send a PR and then we could work on it from there. Sound good?

**Comment by Misplon** [comment]
@adiraomj Sounds good!

Aligning button styles has been a significant support challenge for a long time so this will be a welcome addition.

**Comment by adiraomj** [comment]
@Misplon the settings I have added are _Button Background Color_, _Button Color_, _Button Border Color_, _Remove Button Text Shadow_ and _Remove Button Shadow_. 

I have run into a slight roadblock. How do we go about setting the defaults for the color fields?

For background color we use  a [gradient](https://github.com/siteorigin/vantage/blob/develop/style.css#L312-L316). I have set it to `#ffffff`. Any changes?

For the border color we use 3 different colors for the [border](https://github.com/siteorigin/vantage/blob/develop/style.css#L308-L311). How do we set a default?

**Comment by adiraomj** [comment]
How about giving the border a single color?

**Comment by Misplon** [comment]
@adiraomj Can we perhaps add a value as default setting that's mid-way between the first and last value of the gradients for the background and border?
