### ISSUE TITLE
Add ability to sticky Masthead

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#137]
This request has popped up a number of times via premium support. Basically, the best use case example would be #116 with the Masthead Menu set to blank. A user may wish to create a fully custom header with a custom menu widget present in favour of the base menu. This will be completely possible until the user tries to sticky their newly created header.

**Comment by Misplon** [comment]
We can implement this by migrating the current sticky menu checkbox to a drop down. The drop down would perhaps have three options:

Sticky: Header / Menu / Header and Menu

**Comment by Misplon** [comment]
@gregpriday Think you could investigate this for us? Can we migrate a checkbox into a drop-down?

**Comment by gregpriday** [comment]
The migration part would be double, but messy as usual. We can investigate this at some point.

**Comment by Misplon** [comment]
Cool, closing for now.
