### ISSUE TITLE
Add option for meta text color

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#139]
In North we have used a color setting for `meta text color`. Consider implementing the same in Vantage.

**Comment by Misplon** [comment]
Sounds good. Perhaps after the Page Title Color setting?

**Comment by Misplon** [comment]
The post meta link color is darker. The current color functions in the new settings framework aren't accessible from the old Customizer settings framework. If we don't want to double-up on functionality by adding a new PHP color function we'll need to expand the scope of the new settings framework to allow the old Customizer framework to lighten/darken.
