### ISSUE TITLE
Home page Slider: Add check to ensure Meta Slider is enabled on frontend

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#145]
If you set the home page slider to a meta slider and then disable Meta Slider, the shortcode will be output on the frontend. We should check for Meta Slider before outputting the shortcode to ensure this doesn't happen.

![](https://i.imgur.com/ZY4ouCY.png)

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/vantage/commit/e18bc123a0e2c9852f5cf5bb27c58b6a42b3adb7. Let me know if that works for you @AlexGStapleton

**Comment by Misplon** [comment]
I guess they've changed or removed the constant we were relying on.

**Comment by Misplon** [comment]
Ahh we lost this when we introduce Smart Slider 3 support.
