### ISSUE TITLE
Allow more control over headings (h1, h2, etc)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#146]
A common support request regarding Vantage is more control over the headings. Be it a specific font for the h3,  a slightly larger h2 or a different color h1. People would like slightly more control over them.

At the very least you should be able to adjust the base font size of the headers as currently they're, well... they're not very large. All sub 2em with small .1 increments.

**Comment by Misplon** [comment]
We could add six settings to the Theme Design > Fonts Section starting at the bottom of the existing list.

Content Heading One Size
Content Heading Two Size
Content Heading Three Size
etc.

Assuming that fits.

I'd suggest just doing these settings in px as it's much easier for the user to understand and work with.

**Comment by adiraomj** [comment]
@Misplon do you think we should apply this sitewide or only to headings in `.entry-content`?

**Comment by Misplon** [comment]
@adiraomj At this stage, I'd be included to constrain it to `entry-content`. We could expand it to other areas later if the need/requests come up.
