### ISSUE TITLE
Homepage meta slider is set to demo by default

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#147]
On a fresh install of WordPress if you save your home page (via WP Admin > Appearance > Home Page) it'll automatically set the page meta slider as demo slider.

![](https://i.imgur.com/ayTFkXW.png)

This would be fine but as this page setting will override the customizer home page slider setting if the homepage is set as a static page it leads to confusion why the demo slider is appearing rather than what they selected.

**Comment by Misplon** [comment]
@AlexGStapleton Appearance > Home Page throws a new hurdle into the whole setup but as far as Pages > Home Page and Appearance > Customize go, those settings should be a mirror of each other.

**Comment by AlexGStapleton** [comment]
So #148 is the real issue? And this issue (as in #147) is as a result of that issue? If so, might as well close this then.

**Comment by Misplon** [comment]
Sweet, let's do that. We'll tackle #148 and then see where we are.
