### ISSUE TITLE
If home page is set as static front page the home page slider theme setting doesn't do anything

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#148]
If the home page slider is [set to none](https://i.imgur.com/dvRRQXx.png), and the customizer home page slider is set a slider, nothing will be displayed. If the page is set to none and the customizer isn't, the customizer setting should be used.

**Comment by Misplon** [comment]
@AlexGStapleton nice spot. These settings are meant to mirror each other. If that's broken then ideally that's the issue we should fix in this case.

**Comment by AlexGStapleton** [comment]
When you save the homepage for the first time it'll save as whatever the customer setting is. This means if you had previously set the setting in the customizer to be none, it'll be none. However if you saved the base home page, it'll be set to demo and thus override the customizer.

**Comment by Misplon** [comment]
@adiraomj When we return to Vantage, let's try put this one at the top of the list.
