### ISSUE TITLE
Vantage: Add Upgrade Path to Theme Settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#151]
I know we're not selling Vantage Premium anymore but existing premium users still have it and want to upgrade. It would be a good idea to add an upgrade method when 2.5 is released to allow the user to upgrade to Vantage Premium without having to downgrade to 1.4.4.

**Comment by AlexGStapleton** [comment]
[Andrew's comments on Slack](https://siteorigin.slack.com/archives/themes/p1469473015000026) (purely for reference)

**Comment by Misplon** [comment]
@AlexGStapleton Lots on the go right now. It'll all come into line very soon. You cool with me closing this?

**Comment by AlexGStapleton** [comment]
Yeah sure.
