### ISSUE TITLE
Setting to enable Site Title when logo is set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#152]
People would like to be able to set a logo and the site name be visible at the same time. Something like the following image but with the text actually being text

![](https://i.imgur.com/Yf0iy5D.png)

This is a semi-common customization request and is especially common with the Logo in the Menu masthead.

**Comment by Misplon** [comment]
Comes up enough. Nicely done.

**Comment by adiraomj** [comment]
@Misplon how would you suggest the setting's logic should work? My idea:

label - Display site title alongside logo
description - Only applicable if a Logo Image has been set.

**Comment by Misplon** [comment]
Perfect! (I'm assuming the site title goes after the logo.)

**Comment by adiraomj** [comment]
Yes it does.
