### ISSUE TITLE
Add field to override Site Title for the text logo

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#153]
Certain users have, in the past, asked for the ability to edit the text logo independently of the site title. Thoughts?

**Comment by Misplon** [comment]
Not sure we can assist here dude. We can perhaps offer the Vantage logo PSD file? @gregpriday want to do that?

**Comment by AlexGStapleton** [comment]
I mean that would be ideal to prevent the need for another setting.

**Comment by AlexGStapleton** [comment]
Ideally, we should imo provide as many (at the very least, to Premium users) assets we can so that users can customize them.

**Comment by Misplon** [comment]
Cool. I'll integrate this into the docs. @gregpriday You ok with this? If so, can you send me the Vantage logo PSD if we have it?

**Comment by Misplon** [comment]
Added to: https://siteorigin.com/vantage-documentation/customizing-vantage/theme-settings/logo/.
