### ISSUE TITLE
Use Numeric font weight rather than bold for b and strong

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#155]
It seems that Safari treats font-weight: bold; differently than other browsers. To avoid this issue I think it would be a good idea to switch to [this](https://github.com/siteorigin/vantage/blob/develop/style.less#L94) to a numeric value rather than using bold.

This issue has come up a number of times for me in the past.

**Comment by AlexGStapleton** [comment]
[Andrew's thoughts](https://siteorigin.slack.com/archives/themes/p1469639939000030).

**Comment by adiraomj** [comment]
@AlexGStapleton How do bold elements show up on Safari? I'm not seeing any problem. :)

**Comment by AlexGStapleton** [comment]
Typically not bold while other browsers are.
