### ISSUE TITLE
Grid & Circle Icon Loop: Allow user to define column count

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#157]
You should be able to set the column count. This will overall enhance using these as post loop templates.

**Comment by Misplon** [comment]
I dig this idea but what do you want to do with images? Make them dynamic? Keep in mind they're currently a defined thumbnail size. Ideas?

**Comment by AlexGStapleton** [comment]
That's tricky. I personally would like to see a sizing field akin to the sizing fields in the Widgets Bundle but that might be a bit much. Hm. Maybe we could add a setting to the media page (so we don't clutter the customizer) akin to how [Simple Image Sizes
](https://wordpress.org/plugins/simple-image-sizes/) lets you change image sizes.

Thoughts?

**Comment by Misplon** [comment]
Task: Add to the Blog section a numeric field that would apply to the Grid and Circle Icon loops to set a column count. The field must have a minimum value that equals the current column count. Consider adding to the bottom of the Blog Theme Settings section.

**Comment by AlexGStapleton** [comment]
Sounds good but it should be noted that the circle icons has a column count of three and Grid has a column count of 4.

Forgot to reference [Slack](https://siteorigin.slack.com/archives/themes/p1469713773000004).

**Comment by Misplon** [comment]
Cool, two fields then.
