### ISSUE TITLE
Grid & Circle Icon Loop: Add support for full post and excerpt

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#158]
This is a followup issue to #157 if that change is made the user may decide to use two rows to a loop which could quite easily pull off the full post.

**Comment by Misplon** [comment]
Both the grid and circle loop have a horizontal design so if the user isn't splitting their posts very soon after the title, which is unlikely, full post content could negatively impact the page with long pieces of text pushed into pretty small columns. What we could do is apply the excerpt settings to the grid and post loop templates, allowing the user to control the number of words.

**Comment by AlexGStapleton** [comment]
Do you think #157 would help negate that potential issue? We could maybe set it up so that it's more of a grid system rather than a float system (as in, set in place rather than fit in place).

**Comment by Misplon** [comment]
**Task** Apply the Excerpt Length setting from Theme Settings > Blog to the Grid and Circle Icon loops.

**Comment by AlexGStapleton** [comment]
Looks good. :+1: 

Forgot to reference [Slack](https://siteorigin.slack.com/archives/themes/p1469713773000004).
