### ISSUE TITLE
Add ability to have featured image on page

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#16]
While you can set a featured image for a page, it won't be displayed. It's misleading and should be hidden on pages, or the ability added.

**Comment by gregpriday** [comment]
Good idea, although I'd prefer it if we had this as a page setting option (defaults to off). There are a few situations where you'd use a featured image (like for Facebook og tags). If we change this now, we'll possibly break a few page designs.

**Comment by Misplon** [comment]
@adiraomj Let's hit this once https://github.com/siteorigin/vantage/issues/17 is complete. Thanks dude.

**Comment by Misplon** [comment]
@adiraomj #17 is closed. Let's tackle this when you get a chance. Thanks :)
