### ISSUE TITLE
Add setting to have slider before menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#164]
In the past, certain people have desired for the menu to be displayed after the slider. This has required a child theme in the past and I think it's a decent enough customization that it should be possible in the base version.

**Comment by Misplon** [comment]
Sure, we can consider this. I child themed it a few times. How much demand are you seeing for this @AlexGStapleton? It's quite a complicated setting if we add to the page meta box. It also usually only applies to Logo in Menu which adds further questions and complications. It might be better to leave this one alone and rather put the dev time into one of the new themes on the way.

**Comment by Misplon** [comment]
Sweet. Let's child theme for the moment.
