### ISSUE TITLE
Mobile Menu: Setting enabled by default but not visible until setting resaved in odd manner

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#165]
I've seen a number of reports lately of the mobile menu not working. The fix has always been to disable and then re-enable the setting. The cause of this is the default value of the setting. [By default](https://github.com/siteorigin/vantage/blame/develop/inc/settings.php#L292), it's set to true however it's not stored in such a manner - it's not set (ie. null). This means that the [current checks](https://github.com/siteorigin/vantage/blame/develop/functions.php#L539) we have in place are ignoring it because it's technically "false".

To correct this we'll either need to check for null (and show it) or change the default to false. Alternatively, it might be worth looking into why this setting doesn't save unless it's different to the default as if it had this would be less of an issue (simply save the customizer).

**Comment by Misplon** [comment]
Cool, we'll resolve ASAP. Thanks Alex.
