### ISSUE TITLE
Mobile Menu Collapse: When blank, default to default value

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#166]
I had a user report an issue with his mobile menu and it turned out that he had blanked the Mobile Menu Collapse field. We shouldn't allow this as if the user wishes to disable the field they should, well... disable it.

**Comment by Misplon** [comment]
Sweet. Default to 480.

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/vantage/commit/1185d6d192de64a7ee0019f9dc191725340d9dc6.
