### ISSUE TITLE
Mobile Menu Collapse: When set to 0, always show mobile menu instead of default menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#167]
This is a request I've gotten a couple of times and there's little need to use a setting for it.

Basically, some users wish to have the hamburger menu present at all times. I think it would be a good idea to allow for the user to set the Mobile Menu Collapse to 0 to do this rather than some unnecessarily high amount.

**Comment by Misplon** [comment]
I've always wanted the mobile menu collapse to have a minimum of 480 because so many users set it below 480 and then don't understand why it doesn't work. Making 0 = always on works for me.

**Comment by adiraomj** [comment]
Just a thought: wouldn't there be chance for this to affect backwards compatibility?
Users could have set the  mobile menu to 0 with the intention of eliminating it.

**Comment by AlexGStapleton** [comment]
I feel if they had intentions of disabling it they should have just done that. I suspect the number of people who would be affected by this would be sub 5 at most. Hm, I mean worse comes to worse we could run a check on update to check for a zero value and then reset that field and disable the Mobile menu.
