### ISSUE TITLE
Add ability to disable title without setting page to full width

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#17]
Title pretty much covers it. A template that still had the sidebar but no title would be useful.

**Comment by gregpriday** [comment]
Ideally I'd like to incorporate SiteOrigin Setting's Page Setting component in Vantage. We've tried adding this in the past, but it didn't go too well. I took the wrong approach of completely removing the old page templates and replacing them with page settings.

So if we try this again, we'd need to handle it by only applying the page settings to the default page template so we don't interfere existing page templates. The page settings block will just need to include a note of this.

**Comment by Misplon** [comment]
@gregpriday We could just introduce a new page template: Default - No Page Title. It would be a quick addition and largely free of legacy issues. Given our workload and previous challenges introducing page settings to Vantage, I'd be happy going without them. Keen for a new page template?

**Comment by Misplon** [comment]
Quick meeting. We'll go with the transition to page settings in combination with page templates. @gregpriday when you have time, please, can you add a few details here on how the cross over will work.
