### ISSUE TITLE
Remove function vantage_web_fonts

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#171]
We can delete this bit https://github.com/siteorigin/vantage/blob/develop/functions.php#L350-L360 as the Roboto font is not used anywhere.

@gregpriday do you see any reason not to?

**Comment by gregpriday** [comment]
Yeah, that really shouldn't be there. I think in the past we might have used Roboto as a the site title font, but it doesn't look like that's the case anymore. You can go ahead and remove that.
