### ISSUE TITLE
Readd vantage.pot

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#173]
People unfamiliar with translation have a hard time creating pot files. It also makes it much more convenient for the user to set up a po. Is there any reason why we no longer add it?

**Comment by Misplon** [comment]
Users should ideally be using Loco Translate which handles everything. It's by far the easiest method for normal users to translate their installation. 

I'm not following what the difference is between translating Vantage from a .pot file vs a .po file. You can open either in Poedtior and then save your language files from there. Either way, the user still has to create a new language file for their translation.

**Comment by Misplon** [comment]
@AlexGStapleton Quick look at this when you get a moment. Thanks :)

**Comment by AlexGStapleton** [comment]
Oh sorry, must have missed this.

A pot file is a file generated by PoEdit (for example) and is basically a template for others to build off of. It prevents them from having to find the translated things manually and such.

While a pot can be used as a po file (and vice versa) you're intended to create a template (pot) and then build a po based on the template. Most software will keep this in mind and won't allow you to directly edit the pot file. You will also have a hard time generating a mo file from a pot file.

Loco Translate requires a pot file but you can easily generate one with the plugin - it can miss things so that's something to consider. This is an unnecessary step that can easily be avoided by us including a pot file.

**Comment by AlexGStapleton** [comment]
Disregard this - it's added via the build script. Awkward.
