### ISSUE TITLE
Add ability to adjust Category Archive text on backend

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#18]
I've had a few requests about this and answered a few support threads about it too.

It would be a nice idea to allow the user to be able to edit the Category Archives: [CATEGORY NAME] text on the backend.

**Comment by Misplon** [comment]
I previously would use Loco Translate and as @gregpriday mentioned, create an English translation assuming it was an English site. In inc/template-tag.php, Vantage is still using the older method of handling the archive title with the function `vantage_get_archive_title`. As a result, users can translate the Category Archives and other strings using Loco Translate. However, with North we're using the post WP 4.1 function `the_archive_title`. In the case of North and when we update Vantage my new method would be to install [Code Snippets](https://wordpress.org/plugins/code-snippets/), you can then add a function as follows:

```
function siteorigin_north_archive_title( $title ) {
	if ( is_category() ) {
    	$title = single_cat_title( '', false );
    	} elseif ( is_tag() ) {
        	$title = single_tag_title( '', false );
        } elseif ( is_author() ) {
        	$title = '<span class="vcard">' . get_the_author() . '</span>' ;
        }
    	return $title;
	}
add_filter( 'get_the_archive_title', 'siteorigin_north_archive_title' );
```

When using Code Snippets, remember to advise users to opt for the option that only runs the function on the site front end. The above function will remove the prefix from the category title.

I've definitely thought about adding fields for category archives into theme settings. The challenge is that if you look at the list, there are actually several fields we'd need to add:

https://github.com/siteorigin/vantage/blob/develop/inc/template-tags.php#L314-L355

What we could consider is adding a single setting to the blog section that says something like: Remove the archive heading prefix and then lists an example. @gregpriday What you reckon, just thought of this now.

**Comment by Misplon** [comment]
@gregpriday Page Template settings looking awesome in North, really cool. We'll close this enhancement once they're added to Vantage.

**Comment by Misplon** [comment]
Page settings added to Vantage. Closing.
