### ISSUE TITLE
Customizer home slider stretch setting isn't syncing with Pages - Home

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#182]
The Customizer - Theme Settings - Home - Stretch Slider setting isn't syncing with the Pages - Home - Stretch Slider setting. It does seem to work the other way around through. The page setting is parsing its value to the Customizer.

Video: https://www.dropbox.com/s/kuy9co90ry7i0hj/stretch-sync.mp4?dl=0

**Comment by Misplon** [comment]
Put another way. If both the page setting and Customizer stretch setting is disabled, the Customizer can then stretch the slider. But, if the home stretch setting is enabled first, the Customizer can't turn stretch off.

**Comment by gregpriday** [comment]
@Misplon I think this covers all situations. Can you give it a spin to see if it works for you.

https://github.com/siteorigin/vantage/commit/466024d306ab110f37a143bc100c4b5555573f8c

**Comment by Misplon** [comment]
Legend! Thanks! Will check as soon as I get back to puter.

**Comment by Misplon** [comment]
Resolved via: https://github.com/siteorigin/vantage/commit/466024d306ab110f37a143bc100c4b5555573f8c
