### ISSUE TITLE
Grabbing available templates not working

### ISSUE THREAD

**Issue by cartpauj** [siteorigin/vantage#184]
I'm posting here to hopefully cut out the middle-man between us on this one.

For some reason I'm not able to grab the available custom templates of the theme inside of a custom meta box for our custom post type.

```PHP
  public function register_post_type() {
    $mepr_options = MeprOptions::fetch();
    $this->cpt = (object)array(
      'slug' => MeprProduct::$cpt,
      'config' => array(
        'labels' => array(
          'name' => __('Memberships', 'memberpress'),
          'singular_name' => __('Membership', 'memberpress'),
          'add_new_item' => __('Add New Membership', 'memberpress'),
          'edit_item' => __('Edit Membership', 'memberpress'),
          'new_item' => __('New Membership', 'memberpress'),
          'view_item' => __('View Membership', 'memberpress'),
          'search_items' => __('Search Membership', 'memberpress'),
          'not_found' => __('No Membership found', 'memberpress'),
          'not_found_in_trash' => __('No Membership found in Trash', 'memberpress'),
          'parent_item_colon' => __('Parent Membership:', 'memberpress')
        ),
        'public' => true,
        'show_ui' => true, //MeprUpdateCtrl::is_activated(),
        'show_in_menu' => 'memberpress',
        'capability_type' => 'page',
        'hierarchical' => true,
        'register_meta_box_cb' => 'MeprProductsCtrl::add_meta_boxes',
        'rewrite' => array("slug" => $mepr_options->product_pages_slug, "with_front" => false),
        'supports' => array('title', 'editor', 'page-attributes', 'comments', 'thumbnail')
      )
    );
    register_post_type( $this->cpt->slug, $this->cpt->config );
  }
```

You'll see the "register_meta_box_cb" line. This is where we add the meta boxes for our custom post type. We call **get_page_templates()** inside of MeprProductsCtrl::add_meta_boxes()

But for some reason your templates aren't found. I wonder if it's a timing issue/race condition - you guys have any thoughts?

I wish I was more of a theme guy to troubleshoot this more, I guess what I'm not clear on is if you have to tell WordPress about your templates, or if WordPress just searches for the .php files with the proper headers and adds them automatically?

**Comment by AlexGStapleton** [comment]
Hey mate,

> I wonder if it's a timing issue/race condition - you guys have any thoughts?
It's possible, but without seeing the full code it's hard to tell. What is the hook being used to initiate register_post_type method?

> if WordPress just searches for the .php files with the proper headers and adds them automatically?
That's what it does. [Here's](https://core.trac.wordpress.org/browser/tags/4.6.1/src/wp-includes/class-wp-theme.php#L1024) exactly where it does it.

**Comment by cartpauj** [comment]
`add_action('init', array( $this, 'register_post_type' ), 0);`
I don't think it's a timing issue, but looking over the method in core, I'm not sure why it wouldn't pull them up.

I wonder if https://core.trac.wordpress.org/browser/tags/4.6.1/src/wp-includes/class-wp-theme.php#L1021 clearing the page template cache before we make our call would help. I'll maybe give that a try and report back.

**Comment by cartpauj** [comment]
Whatever the issue is, I don't think it's anything related to MP or your theme. It's working fine on a few test sites of mine apparently: http://cspf.co/hYpt

Not sure why it's breaking on the client's site at this point, but I think we can safely close this out as a non-issue. Sorry to bother, and thanks for the quick response. Very nice theme by the way!

**Comment by AlexGStapleton** [comment]
Good to know. Thanks for testing this one mate. 😄 

Nice product by the way! 👍
