### ISSUE TITLE
Apply a z-index to .site-navigation

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#188]
In certain instances, the sub menu will appear below elements. A good example of this is a Meta Slider Pro layout slider, where it will always happen. As a result of this it would be a good idea to apply a z-index to .site-navigation also (it's currently only applied to .sub-menu).

**Comment by Misplon** [comment]
@AlexGStapleton Can you check this for us?

https://github.com/siteorigin/vantage/commits/develop

Thanks

**Comment by AlexGStapleton** [comment]
Good to go! 👍
