### ISSUE TITLE
Boxed layout: Stretched rows

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#193]
In the boxed layout the default width of rows with a row style applied will exceed the container. It'll look like this:

![](https://i.imgur.com/0nBDXYU.png)

To resolve this issue [this line](https://github.com/siteorigin/vantage/blame/develop/less/widgets.less#L761) needs to be removed as the default .panel-row-style doesn't cause this issue (-35px vs -20px). Here's a before and after gif:

![](https://i.imgur.com/DGQQlG7.gif)

[Reference Layout](https://u.teknik.io/DkzRu.json) - you must enable the boxed layout bound.

**Comment by Misplon** [comment]
Long running issue.
