### ISSUE TITLE
statistics in vantage theme

### ISSUE THREAD

**Issue by fillippoygamboa** [siteorigin/vantage#194]
hello, i installed the theme vantage for my blog, bit now that i started having visitors, cannot find the statistics to do a follow up of how many people is visiting it. i would like to know where do i have a search o what to do in order to get this information. 

thank you very much, 

victoria fillippo

**Comment by AlexGStapleton** [comment]
Unfortunately, this isn't something we can include in a WordPress theme. You'll need to use a third party plugin to do this - [this article](http://www.wpbeginner.com/showcase/7-best-analytics-solutions-for-wordpress-users/) covers a number of solutions that you might like. These plugins require time to gather the relevant stats so unfortunately, any stats prior to installation will not have bene collected.

For future support requests, could you please instead post a thread on our [community forums](https://siteorigin.com/thread/).
