### ISSUE TITLE
Background Image media field is not present on custom home page 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#197]
The recently introduced image media field will not be loaded on a custom home page. This is a huge issue if you edit the custom home page as a page and set the background image via the background image field. Going back to the custom home page editor and saving it will lead to the background image being unset.

Steps to replicate:

Navigate to WP Admin > Appearance > Home Page
Click Edit As Page, open row (or widget)
Set background image via media field
View page, see that image is working
Return to WP Admin > Appearance > Home Page
Save page.
View page, see that image is not working.

Reference GIF:
![](https://i.imgur.com/iYhkgvL.gif)

**Comment by AlexGStapleton** [comment]
This seems to be happening because the meta check fails as there's no post id sent to [vantage_panels_row_style_fields](https://github.com/siteorigin/vantage/blob/develop/inc/panels.php#L214)

**Comment by gregpriday** [comment]
This turned out to be a Page Builder issue. Resolved it in [this commit](https://github.com/siteorigin/siteorigin-panels/commit/98f3de345c028a2b81a6d26e2f59af7cf82892a5).

**Comment by AlexGStapleton** [comment]
Oh well, as long as it's sorted. :)
