### ISSUE TITLE
Logo in Menu: Logo margin style sometimes incorrect

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#198]
It seems to be visible in Safari most easily. The top margin inline style is being incorrectly applied on first load. If you refresh, all is normal.

<img width="1440" alt="margin-top" src="https://cloud.githubusercontent.com/assets/789159/20035483/e6d661f2-a3ee-11e6-9e0f-53847a84c479.png">

Issue has been raised twice this week that I've dealt with.

**Comment by AlexGStapleton** [comment]
Seen this come up an absolute ton. It's typically very easy to override it so I guess I never logged it. 😕 

That's a sick inspector theme by the way. ;)

**Comment by Misplon** [comment]
Thanks for confirming. Cool, let's try get to the bottom of this.

Thanks :) Forget the name, one of the dark ones, perhaps Zero Dark Matrix.
