### ISSUE TITLE
Leave a comment post meta link isn't translatable 

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#2]
Unable to translate the following:

`$comments_link = '<span class="comments-link"><a href="' . get_comments_link() . '">' . get_comments_number_text( 'Leave a comment' ) . '</a></span>';`

Thanks guys.

**Comment by adiraomj** [comment]
@Misplon I think this issue has been dealt with this [commit](https://github.com/siteorigin/vantage/commit/db94a75f209cd1e6214bcba1582ff96f34c8e958). Please check and let me know.

**Comment by Misplon** [comment]
@adiraomj At a glance, that doesn't look right. We still need the `get_comments_number_text` function. Can we not just use that function but remove the optional string we previously had in there. That way we'll be using the WordPress defaults for the strings which will be automatically translated.
