### ISSUE TITLE
Investigate structured data support for pages

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#204]
[Slack Reference](https://siteorigin.slack.com/archives/support/p1478688805000222).

We should add structured data support for pages. Currently, JSON-LD looks to be the best option (as it's super simple) but it may not be compatible with older formats. This is a big deal as it absolutely has to be able to mix and match between the two due to plugins users will use.

If JSON-LD is off the table, We should go with [schema.org](https://schema.org/).

References:

- [Introduction to Structured Data - Google](https://developers.google.com/search/docs/guides/intro-structured-data)
- [Google Structured Data testing tool](https://search.google.com/structured-data/testing-tool)

**Comment by Misplon** [comment]
@gregpriday confirmed JSON-LD would fall under plugin territory.

**Comment by Misplon** [comment]
Looking into a plugin for this.

**Comment by Misplon** [comment]
Tried this but see now no author reference: https://wordpress.org/plugins/wp-seo-structured-data-schema/.
