### ISSUE TITLE
Meta Slider: Account for differnt WPML sliders

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#211]
Okay so with the recent change to resolve #148, it's not possible to set sliders for different languages for the homepage.

**Comment by Misplon** [comment]
Hey man, unfortunately not, this is a hard limitation. We arrived here after sorting out several other sync. issues between the page setting sending info to the Customizer.

**Comment by Misplon** [comment]
Cool, docs updated.

**Comment by AlexGStapleton** [comment]
Ah, fair enough.. I'll point the user in the direction of the docs. 👍

**Comment by Misplon** [comment]
Sweet. So TLDR is we're falling back on adding the slider with Page Builder and then using Page Settings to handle the gap below the menu.
