### ISSUE TITLE
Add link to the box author

### ISSUE THREAD

**Issue by fitrizulkarnain** [siteorigin/vantage#213]
How to add link to the box author on last post content template? If I click the author image (profile photo’s), we redirect to their profile URL. How to I applying this issue?
![author box](https://cloud.githubusercontent.com/assets/25887494/23107787/9d8ffdac-f73e-11e6-8c8a-1b1ece006840.jpeg)

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/commit/4092de741d2c8b9e91a8da5de96c4f1fe96feeb8
