### ISSUE TITLE
Scroll to Top functionality on mobile is directly tied to mobile menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#214]
Is there a specific reason why the scroll to top functionality needs to be tied directly to the menu?([Refernece in code](https://github.com/siteorigin/vantage/blob/develop/js/jquery.theme-main.js#L21) - specifically the isMobileNav check) I can see quite a few instances where user's may wish to not have a menu (in favor of a custom menu widget for example) but still wish to retain the scroll to top functionality.

**Comment by Misplon** [comment]
This conditional hasn't been updated after the new masthead widget area was added. We can update it.

**Comment by Misplon** [comment]
@AlexGStapleton https://github.com/siteorigin/vantage/commit/991a97fb9a4f2d7e18f857c66dd0e0692b0cf22c 

Cool?

**Comment by AlexGStapleton** [comment]
Yep! 👍  :)
