### ISSUE TITLE
FireFox 52: Scroll to top disappears when it should be visible

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#215]
FireFox 52 (the latest version) is having issues with how we handle the scroll to top button. Basically, on initial scroll, it'll display correctly and then disappear.

Can be replicated on [demo site](https://demo.siteorigin.com/vantage/).

![](https://i.imgur.com/60BzV9N.gif)

**Comment by gregpriday** [comment]
This is fixed in Firefox 53 and 54 (beta) on Windows.
