### ISSUE TITLE
WooCommerce: Add Gallery spacing

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#216]
The WooCommerce lightbox is working now after c3795558c60d6946c5c086ca536fde33a9ac2681 but the padding previously applied to WooCommerce gallery images is no longer present. I suspect WooCommerce changed how it's structured so our old CSS no longer works with it.

![](https://i.imgur.com/8a7PTra.png)

**Comment by Misplon** [comment]
Ahh I only added the margin below the main image, didn't test with a full gallery. Will resolve.

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/commit/846a108e61f4e3ab9006711c6e07500987f2e3e0
