### ISSUE TITLE
Custom Home Page: Certain row design settings aren't saved / removed upon save

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#219]
Most row style design settings aren't saved when using the custom home page functionality. The settings that aren't saved are the background image, background image display, and border colors. These settings are removed if they were set via the full editor. I suspect this issue is related to the legacy theme settings group and the 2.5 update.

**Comment by Misplon** [comment]
@adiraomj We, ideally, need to try sort this one out. Greg is a bit locked down at the moment. He's usually the one to take care of these legacy challenges. Perhaps you'd be keen to take a look and see if you can spot the issue?

**Comment by adiraomj** [comment]
I'll work on this later today. :)

**Comment by Misplon** [comment]
Awesome, thanks :)

**Comment by Misplon** [comment]
Closing. We'll resolve via https://github.com/siteorigin/siteorigin-panels/issues/441.
