### ISSUE TITLE
Support Breadcrumb NavXT

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#22]
We could add support for Breadcrumb NavXT plugin in addition to Yoast SEO. Similar to what we have done for North.

**Comment by gregpriday** [comment]
You can go ahead and add this. Would be a nice addition.

**Comment by adiraomj** [comment]
@gregpriday should I change the function name to `vantage_display_breadcrumbs` and the filename to `breadcrumbs.php`. The naming would be more appropriate with this update.

**Comment by gregpriday** [comment]
You're right. The only thing we need to think about here is child themes that have already overwritten the `vantage_display_yoast_seo_breadcrumbs` function. So what I'd suggest is this:

We remove the `vantage_display_yoast_seo_breadcrumbs`, and replace it with the broader `vantage_display_breadcrumbs ` function. Then in the `vantage_display_breadcrumbs` function, we check if the old `vantage_display_yoast_seo_breadcrumbs` function exists (being defined by the child theme), and just call that. If it doesn't exist, then `vantage_display_breadcrumbs` would continue with its normal logic.

Do you think that would work?

**Comment by adiraomj** [comment]
Nice.. Seems like the best way to go..
