### ISSUE TITLE
Question about the Circle Widget

### ISSUE THREAD

**Issue by troppuissant** [siteorigin/vantage#224]
Hi,

I was questioning if there is someone that can make you add a link to a circle widget without "more url' link.. So that the icon and title are clickable.
If someone could help me out with that would be great!

Thanks in advance!

**Comment by Misplon** [comment]
Hi @troppuissant. If you have the SiteOrigin Widgets Bundle plugin installed you can rather use the SiteOrigin Features Widget. It will let you add a More URL with no More Text. Enable the options Link feature title to more url and link icon to more URL. Those checkboxes are found at the bottom of the Features widget.

**Comment by Misplon** [comment]
Closing. Let me know if you have any follow-up questions. Cheers :)
