### ISSUE TITLE
Blog post featured images are blurry

### ISSUE THREAD

**Issue by ibrossiter** [siteorigin/vantage#226]
The featured image used for a post shows up blurry on both archive and single post page

**Comment by ibrossiter** [comment]
Might need retina support

**Comment by Misplon** [comment]
Try running [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) and see if the issue resolves.

**Comment by Misplon** [comment]
@ibrossiter Let me know how this went. Thanks.

**Comment by Misplon** [comment]
@ibrossiter Quick check here when you can. Thanks pal. Trying to thin this list out a bit.

**Comment by ibrossiter** [comment]
Hey Andrew. I used Regen and still blurry.

**Comment by Misplon** [comment]
Cool please send a URL I can check. Shot

**Comment by ibrossiter** [comment]
http://vantage-demo.packs.siteorigin.com/blog/

**Comment by ibrossiter** [comment]
Blurry on Retina Display

**Comment by Misplon** [comment]
@ibrossiter Please, can you try adding an image twice the size but still inserting Medium or Large and let me know if the issue resolved. Thanks.

**Comment by ibrossiter** [comment]
the original featured images was 1920 x 1307. I then uploaded the full image at 4700 x 3200. Still no difference.

**Comment by ibrossiter** [comment]
http://vantage-demo.packs.siteorigin.com/blog/

**Comment by Misplon** [comment]
Thanks. Will take a look tomorrow.

**Comment by Misplon** [comment]
@adiraomj I briefly looked at this challenge. Any chance you'd want to take this on? Adding a larger featured image size for high definition displays.
