### ISSUE TITLE
WP Logo Set and No Widget Overlay issue

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#227]
If the logo is set through WP Logo functionally **(WP Admin > Appearance > Customize**, **Site Identity**) and **No Widget Overlay** is enabled, and there's a widget in either the Header or Masthead widget area, JS errors will result due to [No Widget Overlay looking for a different structure](https://github.com/siteorigin/vantage/blob/develop/js/jquery.theme-main.js#L392).

![](https://i.imgur.com/uVOGKTX.png)

(make sure to unset the Logo set through theme settings first or this issue may not occur).

**Comment by Misplon** [comment]
@adiraomj Please, can you attend to this one for us.

**Comment by Misplon** [comment]
@AlexGStapleton I'm unable to replicate at this time, please can you confirm and close if I'm correct. Thanks.

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this either anymore. I also haven't received any reports of this happening lately. This must have been indirectly fixed at some stage.
