### ISSUE TITLE
Update Font Awesome to 4.7

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#232]
Vantage includes version 4.6.2 of Font Awesome, which is [two versions behind the latest version](https://github.com/FortAwesome/Font-Awesome/releases).

[Requested here](https://siteorigin.com/thread/will-vantage-be-updated-for-font-awesome-4-7-2/).

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/commit/c4d234f00032dc7694d577bde87a8beb523726b4
