### ISSUE TITLE
Mobile Nav HTML applied to Max Mega Menu Instances

### ISSUE THREAD

**Issue by tomhemsley** [siteorigin/vantage#233]
In functions.php there is a quick check to make sure Max Mega Menu is not enabled on the Primary menu location before the mobilenav.php file is included. This works as expected when MMM has been enabled for the main menu.

However, if the user has created a _new_ menu location to use Max Mega Menu with, but _not_ enabled MMM on the Primary location, the mobilenav.php functionality is included and will be applied to the new menu location (even though MMM has been enabled for that location).

I can see a quick fix, adding the following to the siteorigin_mobilenav_nav_filter function in mobilenav.php

`if ( function_exists( 'max_mega_menu_is_enabled' ) && max_mega_menu_is_enabled( $args->theme_location ) ) {
	return $nav_menu;
}`

**Comment by Misplon** [comment]
Resolved in https://github.com/siteorigin/vantage/commit/b251c524a22f075f1c1d63ca4e5a16242d4bc966.

**Comment by Misplon** [comment]
Thanks Tom, will update the theme ASAP. Appreciate your feedback on this.

**Comment by tomhemsley** [comment]
Great, thanks Andrew!

**Comment by Misplon** [comment]
For sure :) Thanks again for your feedback.
