### ISSUE TITLE
Add color settings for the responsive menu

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#24]
Add settings to control the colors of the mobile menu, similar to what we have in North. Currently, the arrows for sub-menus are images so we'll need to move those after to FontAwesome or similar. I'm not sure the Navigation section is the best place for these settings. We could perhaps create a new section called Mobile Menu and take any mobile menu settings currently in Navigation and put them in this new section with the new color settings.

**Comment by adiraomj** [comment]
Would you also like me to change the back and close links to font awesome icons?

**Comment by Misplon** [comment]
Sorry for the delay in replying. Yes, we'll need to change all of the current image icons to font icons. They're white now so the most common issue we'd see if we left them would be users setting the background to white and the icons no longer being visible.
