### ISSUE TITLE
PHP warning when installing recommended plugins

### ISSUE THREAD

**Issue by Shelob9** [siteorigin/vantage#246]
`Warning: sprintf(): Too few arguments in /app/wp/wp-admin/includes/class-bulk-upgrader-skin.php on line 150`

![screen shot 2018-02-09 at 10 00 38 am](https://user-images.githubusercontent.com/1994311/36033883-2d80c560-0d80-11e8-8011-3fb5549d3276.png)

**Comment by AlexGStapleton** [comment]
```
( ! ) Warning: sprintf(): Too few arguments in C:\wamp64\www\siteorigin\sitepack\mono\wp-admin\includes\class-bulk-upgrader-skin.php on line 150
Call Stack
#	Time	Memory	Function	Location
1	0.0069	431840	{main}( )	...\themes.php:0
2	0.0105	503072	require_once( 'C:\wamp64\www\siteorigin\sitepack\mono\wp-admin\admin.php' )	...\themes.php:10
3	1.1573	34271376	do_action( )	...\admin.php:224
4	1.1573	34272088	WP_Hook->do_action( )	...\plugin.php:453
5	1.1573	34272168	WP_Hook->apply_filters( )	...\class-wp-hook.php:310
6	1.1573	34272968	call_user_func_array:{C:\wamp64\www\siteorigin\sitepack\mono\wp-includes\class-wp-hook.php:286} ( )	...\class-wp-hook.php:286
7	1.1573	34273560	TGM_Plugin_Activation->install_plugins_page( )	...\class-wp-hook.php:286
8	1.1579	34284040	TGMPA_List_Table->process_bulk_actions( )	...\class-tgm-plugin-activation.php:658
9	4.8044	35269712	TGMPA_Bulk_Installer->bulk_install( )	...\class-tgm-plugin-activation.php:2892
10	4.8241	35283704	TGMPA_Bulk_Installer->run( )	...\class-tgm-plugin-activation.php:3289
11	4.8241	35284424	WP_Upgrader->run( )	...\class-tgm-plugin-activation.php:3173
12	9.8606	35291888	TGMPA_Bulk_Installer_Skin->after( )	...\class-wp-upgrader.php:759
13	9.8606	35292384	Bulk_Upgrader_Skin->after( )	...\class-tgm-plugin-activation.php:3553
14	9.8607	35292528	sprintf ( )	...\class-bulk-upgrader-skin.php:150

```

**Comment by AlexGStapleton** [comment]
Related: https://github.com/TGMPA/TGM-Plugin-Activation/pull/670

Seems to be fixed in an update to TGM but as far as I can tell that version hasn't been released. I know it's not ideal, but it may be a good idea to edit the files and apply the patches directly. Thoughts @Misplon?

**Comment by Misplon** [comment]
Thanks for the heads up @Shelob9. Appreciate it :) We'll update TGM as soon as they push the release.

**Comment by MiGzY** [comment]
In the meantime..
Warning: sprintf(): Too few arguments in \wp-admin\includes\class-bulk-upgrader-skin.php on line 150

Had to fix with:
Old Code:
if ( $this->result && ! is_wp_error( $this->result ) ) {
if ( ! $this->error ) {
echo '

' .
'
' . sprintf( $this->upgrader->strings['skin_update_successful'], $title ) .
' ' . __( 'Show details.' ) . '' .
'

';
}
echo '<script type="text/javascript">jQuery('.waiting-' . esc_js($this->upgrader->update_current) . '').hide();</script>';
}
New Code:
if ( $this->result && ! is_wp_error( $this->result ) ) {
if ( ! $this->error )
echo '

' . sprintf($this->upgrader->strings['skin_update_successful'], $title, 'jQuery('#progress-' . esc_js($this->upgrader->update_current) . '').toggle();jQuery('span', this).toggle(); return false;') . '

';
echo '<script type="text/javascript">jQuery('.waiting-' . esc_js($this->upgrader->update_current) . '').hide();</script>';
}

**Comment by Bitmaudit** [comment]
Warning: sprintf(): Too few arguments in class-profile-magic-admin.php on line 192

**Comment by AlexGStapleton** [comment]
Hi @Bitmaudit ,

I'm sorry that you've experienced this issue. We can't seem to replicate this issue at the moment. Can you please clarify what version of PHP, WordPress, and Vantage you're using?

**Comment by Remzi1993** [comment]
@Misplon Did you update TGMPA? I suggest to use the latest develop version: https://github.com/TGMPA/TGM-Plugin-Activation (it's stable and fixes some things)

**Comment by AlexGStapleton** [comment]
@Remzi1993 Thanks for the heads up. We'll try the development version of TGMPA shortly.

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/vantage/pull/323.
