### ISSUE TITLE
Increase Font Size of certain elements when on mobile devices to increase readability (as per PageSpeed Insights recommendation) 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#26]
Very minor thing but it'll appease certain people. :confused: The font size of certain elements, typically the post meta, and comment related sections have very small "tap areas" (12px font-size). From what I can tell, typically if you increase it to 13px or 14px on mobile Google considers it large enough. Making this will increase set our defualt mobile experince to 100%.

Reference Links:
[Blog Post](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.siteorigin.com%2Fvantage%2F2013%2F09%2F27%2Fabsorbed%2F) (demo site - it's under User Experience)

**Comment by gregpriday** [comment]
@adiraomj would you like to handle this? If you do, maybe you could check around for any other enhancements we could make. Or does this really get us up to 100%?

**Comment by adiraomj** [comment]
I can handle this. I'll have a look to see what we can do. :)

**Comment by gregpriday** [comment]
@adiraomj have you had a chance to take a look at this?

**Comment by adiraomj** [comment]
Yes I have. I'll send a PR later today. :)

**Comment by gregpriday** [comment]
Perfect. Once we've finished all the [P1](https://github.com/siteorigin/vantage/labels/priority-1) issues, I'll start preparing the update.
