### ISSUE TITLE
Build issue with pot file: directory incorrectly named as vantage.pot

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#264]
There's an issue with the build system that is resulting in the Vantage language directory `vantage/languages/` to be incorrectly named. Instead of just `vantage`, it's called `vantage.pot`.

![](https://i.imgur.com/wcbk9D9.png)

@Misplon tried a release build test and the same issue occurred again. We also checked Corp and this issue wasn't occurring for that theme so it's unlikely (but still possible) to be a general theme build script.

**Comment by braamgenis** [comment]
@AlexGStapleton @Misplon Could you guys try the following:

1. Delete the `node_modules` folder in the `build` folder in vantage.
2. Run `npm install` in the `build` folder.

Then try do another build.

**Comment by Misplon** [comment]
Thanks @braamgenis, I'll get on that this evening and push an update for Vantage as soon as I'm done.
