### ISSUE TITLE
Duplicated menu in customizer

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/vantage#285]
Similar to #240, but not exactly the same.

Steps to reproduce:

- Open customizer with Vantage active
- Make any change which causes the customizer preview to refresh.
- Two menus are rendered.

**Comment by gregpriday** [comment]
I can't seem to recreate this. Is it still any issue. @Misplon or @AlexGStapleton - can either of you check?

**Comment by Misplon** [comment]
I can't replicate this. Changing the Layout Bound setting definitely forces a refresh, I'm not seeing a duplicated menu. @AlexGStapleton ?

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this either.

**Comment by Misplon** [comment]
Cool, let's close for the moment, if it comes up again, we can re-open.

**Comment by braamgenis** [comment]
Heisenbug!
