### ISSUE TITLE
CSS Grid - Flexbox support?

### ISSUE THREAD

**Issue by ivanbuncic** [siteorigin/vantage#299]
Hi guys/gals, 

I really love Vantage theme!

What is your timeline look like, how about adding CSS Grid or Flexbox support to this marvelous theme.
Did you even consider it?

Thanks!

**Comment by Misplon** [comment]
Hi Ivan

Thanks for reaching out :)

Our Page Builder plugin uses Flexbox. Unfortunately, at there moment there aren't any plans to add CSS Grid or Flexbox natively to Vantage.

Sorry, I don't have better news. All the best.
