### ISSUE TITLE
Remove or update word-break property

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#3]
https://github.com/siteorigin/vantage/blob/develop/style.css#L155

Remove `word-break` property or update the value to normal. Normal is the default so recommend we remove.

**Comment by gregpriday** [comment]
@Misplon: I'm fairly sure this comes from the default reset code. Is it causing problems?

**Comment by Misplon** [comment]
@gregpriday I actually might have been involved the adding of this mistake originally. My bad. The declaration I've highlighted is just outside of reset, it's in global and it's incorrect. 

TLDR: Remove this line please: https://github.com/siteorigin/vantage/blob/develop/style.css#L155

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/commit/c92f3a8179f0d7cf209c2c3f7cdcbb863e9b4b1b
