### ISSUE TITLE
Meta Slider Pro addons showing in Meta Slider

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#31]
Our Meta Slider Pro addons for Vantage are showing up in Meta Slider Free in open space when no slider has been added:

<img width="1427" alt="meta-slider-problem" src="https://cloud.githubusercontent.com/assets/789159/15190058/386a555a-17ae-11e6-83bb-ec2ffc4c86aa.png">

**Comment by gregpriday** [comment]
I'll remove this integration.

**Comment by gregpriday** [comment]
@Misplon - can you check if this is fixed in develop? Should be resolved with https://github.com/siteorigin/vantage/commit/b30c196c4e41dfe50a37634e4f323b19ec892c26
