### ISSUE TITLE
Ability to customize scroll to top coloring

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#32]
You should be able to adjust the scroll to top colouring to better suit your websites colouring. 
Oddly, there doesn't seem to be a default hover so it would be a good idea to introduce that also for UX reasons.

Ideal settings:

- background
- background hover
- color
- color hover

**Comment by adiraomj** [comment]
I  was just wondering if we actually need 4 fields. We could just have the background and color fields.
The element could be set to have an opacity of 0.3 as default and 0.8 on hover. What do you guys think?

**Comment by Misplon** [comment]
@adiraomj I'd be cool with that. One setting for background, one setting for text and we use the current normal and hover state opacity settings.
