### ISSUE TITLE
Home Page: If custom slider is set, demo slider will be shown

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#342]
This issue is related to #341

If a custom slider has been set for the home page, but the slider plugin powering that slider has been disabled, the demo slider will be shown instead of nothing.

**Comment by Misplon** [comment]
**Sequence:**

Set Home Slider to None from page or Customizer setting.
Activated Smart Slider.
Set a home slider from page or Customizer setting.
Deactivated Smart Slider.

**Results:**

The page-level setting holds its None value.

<img width="217" alt="page" src="https://user-images.githubusercontent.com/789159/70372305-f8dc8380-18e5-11ea-9e3e-e6b619a66e8d.png">

The Customizer setting doesn't hold its None value.

<img width="295" alt="Customize__Front_Page_-_SiteOrigin" src="https://user-images.githubusercontent.com/789159/70372332-2f1a0300-18e6-11ea-848c-719013e3fe21.png">
