### ISSUE TITLE
Posts page: Post titles aren't outputting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#35]
The blog page isn't displaying post titles. Post titles are however displaying in category archive pages. The blog page issue applies both "Front page displays: Your latest posts" and to a defined posts page.

**Comment by adiraomj** [comment]
@Misplon I cannot seem to replicate the issue. Can you check the **Page Template Settings** for the the **Blog Page** in the customizer and see if the **page title** is checked?

**Comment by Misplon** [comment]
@adiraomj Quite right, it was off. What confused me is that I used https://wordpress.org/plugins/wordpress-database-reset/ to reset. After resetting, the page title checkbox is disabled. I see that the default is set to `true`. Any idea why it resets to false when Masthead Bottom Margin and Footer Top Margin and reset to `true`?

**Comment by adiraomj** [comment]
No idea. It has to be an issue with the settings framework. What do you think @gregpriday?

**Comment by Misplon** [comment]
Here is my video showing steps to reset.

https://dl.dropboxusercontent.com/u/3072682/vantage-post-titles-after-reset.mov

**Comment by gregpriday** [comment]
@Misplon - was this issue fixed with [this commit](https://github.com/siteorigin/vantage/commit/878e6f75396103de13cfb1871a2315b841b0ae16)?

**Comment by Misplon** [comment]
Seems fine now, below is after resetting options.

<img width="911" alt="customize__june_2016_ _siteorigin_vantage_" src="https://cloud.githubusercontent.com/assets/789159/15991984/c877ca20-30c1-11e6-8a81-4afbab5d48f5.png">

After reset it is disabled when checking the blog page but I've just realised that's normal as the blog/posts page doesn't render the title.
