### ISSUE TITLE
Circle Icon Post Loop: Posts per page ignored

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#361]
To replicate the issue, insert a Post Loop widget into a page, set Posts Per Page to 9, and the template to Circle Icons. 10 posts are outputted, the count is ignored.

**Comment by AlexGStapleton** [comment]
I looked into this was able to replicate this and noticed this issue occurred with any template I tried. I then noticed that I had a sticky post set and that was what was bumping the posts over 9. Do you have any sticky posts? If so, try excluding them it to see if that results in the exact number of posts.

**Comment by Misplon** [comment]
Ahh yeah, that's it. Thanks for taking a look!
