### ISSUE TITLE
Investigate External Background Image not being imported

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#388]
This is likely related to the legacy Theme Row Styles

**Comment by AlexGStapleton** [comment]
@Misplon I'm only really able to replicate the background not importing when editing an older legacy page (one that has the theme row styles). Is that the case for you also?

**Comment by Misplon** [comment]
Yeah, if I create a new page then the issue doesn't persist. Should we leave this?

**Comment by AlexGStapleton** [comment]
If you can't easily replicate this I'm happy with leaving it.
