### ISSUE TITLE
Resolve outstanding jQuery Migrate warnings

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#390]
* Check https://github.com/siteorigin/vantage/blob/develop/js/keyboard-image-navigation.js for any items that need updating.
* Ensure that jquery.flexslider.js has been minified. It doesn't seem like our changes are present in the minified version.

Ref: https://wordpress.org/support/topic/vantage-causing-many-jquery-errors-on-my-site/.

**Comment by AlexGStapleton** [comment]
I've checked the linked thread and the reports related to Vantage are all from January. We released an update roughly ten days prior to these logs which contained the changes made in https://github.com/siteorigin/vantage/pull/374.

To confirm this suspicion, I've double-checked each of the reports, and they're not valid in the current release. For example:
`
2021-01-24 23:32:46 	jQuery.fn.keydown() event shorthand is deprecated 	Theme: Vantage vantage/js/keyboard-image-navigation.min.js`

That would suggest that [this line](https://github.com/siteorigin/vantage/blob/develop/js/keyboard-image-navigation.js#L5) was how it used to be https://github.com/siteorigin/vantage/commit/e503445cb7fc8d0385f512b2de67aa392f4fdb7d#diff-2115a708ff0f5c05a2f54a6f971c66d1fd70d6992459536bf9e43da3336f7c72L5.

> Ensure that jquery.flexslider.js has been minified. It doesn't seem like our changes are present in the minified version.

That's minifying without issue. You can verify this by blanking the file and adding `console.log(123);`. Create a build and check the minified js/jquery.flexslider.min.js and you'll see the test code. Can you please clarify what you're seeing?

**Comment by Misplon** [comment]
Super, thanks for taking a look.
