### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by warpcoil** [siteorigin/vantage#396]
Hello, this is a subjective issue, so you may disagree with come WCAG points.

Tabs stops, lead from logo onto search icon then back again to the first element of the menu, then the next element.  Is this by design? [i.e. when you press tabs, the seemingly natural order is not adhered to].

Tested with Accessibility Insights.

Also with the demo you may notice contrast issues: https://vantage-demo.packs.siteorigin.com/

Tested with Google Lighthouse.

Hope those issues helps and look forward to your insights.

Kind Regards

Bobby

**Comment by Misplon** [comment]
Hi Bobby

Thanks for reaching out.

I'll ask one of our developers to take a look at the Vantage tab order and advise further.

Vantage, unfortunately, wasn't built as an accessibility-ready theme so defaults and demo sites are unlikely to satisfy contrast requirements. That said, all theme colors can be adjusted via Appearance > Customize > Theme Design so hopefully, you can make up for any shortfalls in that area.

Kind regards

Andrew

**Comment by warpcoil** [comment]
That is perfect.  I can confirm the colour options in "customization" options do indeed resolve the issue for us on our site.  Whether you want the demo to conform, that's none of my business :)

Thank you for looking into the tab ordering, it's very welcome.

**Comment by AlexGStapleton** [comment]
Hi Bobby,

Thanks for the heads up on the tabbing. I agree with your assessment and I've made some changes in https://github.com/siteorigin/vantage/pull/397 to rectify this.

Kind regards,
Alex
