### ISSUE TITLE
social media share buttons not showing up anymore

### ISSUE THREAD

**Issue by jrfx85** [siteorigin/vantage#399]
Not showing all social media buttons in blog posts:
class="network facebook" not working anymore

**Comment by Misplon** [comment]
Hi, thanks for reaching out. If you're using Vantage Premium, unfortunately, it was discontinued in 2016. We're still supporting the version of Vantage hosted on WordPress.org. https://wordpress.org/themes/vantage/. The sharing buttons weren't migrated to the free version though as they are considered plugin-level functionality. You could perhaps consider a plugin like https://wordpress.org/plugins/wp-socializer/.

**Comment by jrfx85** [comment]
Hi, thank you very much for the fast reply...i'll use the wp-socializer 
plugin

bye

Am 29.08.2021 20:13, schrieb Andrew Misplon:

**Comment by Misplon** [comment]
Sure, no problem.

If you'd like to migrate to the version of Vantage hosted on WordPress.org you can do so by switching to any other theme, deleting Vantage, and then reinstalling via Appearance > Themes > Add New. Use the search form in the top right to search for Vantage. You can also download the theme ZIP file from https://wordpress.org/plugins/vantage and install the ZIP file from Appearance > Themes > Add New > Upload Theme. Overwriting the existing theme when prompted. It's worthwhile making a site backup beforehand.

In the event you'd like to make use of SiteOrigin Premium, please, email support@siteorigin.com for a discount code. 

Cheers for now :)
