### ISSUE TITLE
FitVid: Add Support for WooCommerce only pages (such as Shop)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#40]
If you add a video to the shop page in WooCommerce, it won't be affected by FitVid. This is due to the WooCommerce shop page making use of a "custom" archive template. Specifically, it doesn't follow the exact structure [outlined here](https://github.com/siteorigin/vantage/blob/develop/js/jquery.theme-main.js#L15).

If you add .woocommerce #main to the selector, it'll work as desired. Please note that you can't use our typical .site-content class as this wrapper is generated by WooCommerce.

**Comment by AlexGStapleton** [comment]
Just to clarify, I'm not sure if this is happening on other pages but the .woocommerce #main fix should resolve it when it does.

**Comment by gregpriday** [comment]
Very well spotted!
