### ISSUE TITLE
Accessibility Test

### ISSUE THREAD

**Issue by warpcoil** [siteorigin/vantage#410]
Issue Priority: Low

Hi, so we do a lot of testing on accessibility (and the Vantage theme is very good when set up correctly by the user).

One thing I have noticed that if you mouse-over an a menu item you get the theme colour (set in Customisation Options), whereas if you "tab" into the menu, you get the base css colour #00bcff. In our case the "Hover Background" colour is #1c6894 but those with motor issues use the keyboard.

It's a simple fix, I might get chance to look at for you at the weekend or you can; it's entirely up to you.

**Comment by Misplon** [comment]
Hi Bobby

Thanks for letting us know about the issue. I've hopefully, resolved it via https://github.com/siteorigin/vantage/pull/411. Please, find a beta release [here](https://siteorigin.com/wp-content/uploads/2022/01/vantage.1.19.6-beta.zip).

If I've missed anything, please, let us know.

Thanks again.

Andrew

**Comment by Misplon** [comment]
Hi Bobby

Thanks for testing and letting us know; I appreciate it.

Cheers for now.

Andrew
