### ISSUE TITLE
Alternative to Google Web Fonts

### ISSUE THREAD

**Issue by christianhauff** [siteorigin/vantage#414]
As to a current legal discussion in Germany, there is the possibility that the usage of google fonts might bring a website owner in legal problems, see [here](https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/).

Is there a possibility that an alternative to using the predefined array of fonts can be implemented, e.g. to just set an url to a selfhosted font?

**Comment by Misplon** [comment]
Hi Christian

Thanks for reaching out. Please, see the following [filter](https://siteorigin.com/vantage-documentation/advanced-customizations/#heading-disable-google-fonts).

**Comment by christianhauff** [comment]
Hi @Misplon 
great, thank you. Haven't seen that in the docs!

**Comment by Misplon** [comment]
Thanks for taking a look. Hopefully, the filter is helpful.

Cheers

Andrew
