### ISSUE TITLE
Consider expanding Vantage Social Media widget networks

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#46]
Consider adding more networks or all available networks to the Vantage Social Media widget.

**Comment by Misplon** [comment]
@adiraomj chatted with Greg, let's add the available Font Awesome social networks. Thanks :)

**Comment by adiraomj** [comment]
I was thinking of adding

- 500px
- Behance
- Bitbucket
- Codepen
- Deviantart
- Medium
- Mixcloud
- SoundCloud
- Stumbleupon
- Tumblr
- WordPress

Anything more/less?

**Comment by gregpriday** [comment]
That list looks good to me.

**Comment by braamgenis** [comment]
What about GitHub? :grin:

**Comment by gregpriday** [comment]
Oh yeah, of course!
