### ISSUE TITLE
Responsive Menu: When menu item URL is empty it should open sub menu on click

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#47]
This is a UX fix. Users typically presume an empty URL menu item field should act as a # does. The normal menu allows for this but the responsive menu does not. Instead it will close the responsive menu.

**Comment by Misplon** [comment]
@AlexGStapleton @adiraomj  and I haven't been able to replicate this issue. When you click a parent menu item with a `#` link , it opens the sub-menu pane, both the link text and the arrow do so. Please, can you confirm. Thanks.

**Comment by AlexGStapleton** [comment]
My mistake - it was a completely empty URL. I think both should work. Thoughts?

![](https://i.imgur.com/1huQN5T.png)

**Comment by adiraomj** [comment]
I think users will have to use `#` in such cases. If left empty, the anchor becomes 
`<a class="link">...</a>` 
as opposed to 
`<a href="#" class="link">...</a>`

An element with `href` is a link which is clickable. An a element without `href` is just a placeholder and not clickable.

**Comment by Misplon** [comment]
@AlexGStapleton I'm ok with leaving if this if you are. If this comes up again we can ask users to insert a `#` and all should be good.

**Comment by AlexGStapleton** [comment]
That's fine.
