### ISSUE TITLE
Unable to full screen YouTube embed in IE11

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#5]
[Issue was reported in this thread](https://siteorigin.com/thread/vantage-theme-not-allowing-youtube-video-to-go-to-full-screen/).

IE11 won't allow users to fullscreen embed YouTube videos. Able to reproduce locally with the following embed:
`<iframe class="video_view9_img" width="720" height="430" src="//www.youtube.com/embed/G6cLbHNaDW0" style="border: 0;" allowfullscreen=""></iframe>`

A quick Google produced no solutions. I hope someone besides me runs Windows. :worried:

**Comment by gregpriday** [comment]
Closing this from what I understand about your follow up.
