### ISSUE TITLE
Page Settings: Consider adding a setting to remove the bottom bar

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#50]
Consider adding a page setting to remove the bottom bar below the footer widgets.

**Comment by adiraomj** [comment]
Do you mean the theme attribution?

**Comment by Misplon** [comment]
@adiraomj Indeed. Because user can remove everything else, for a landing page situation, I think they should be able to remove that too.

**Comment by adiraomj** [comment]
@Misplon I think this is going to be a premium feature.

Go to **Theme Settings** -> **General** -> **SiteOrigin Attribution**.

Once the checkbox appears with the premium plugin the bar can be removed. :)
