### ISSUE TITLE
Header Settings: Consider making header widget and header text settings conditional

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#51]
When using the Logo in Menu layout the Header Text and Header Widget Area don't output. Consider making these two conditional.

@gregpriday. Keen?

**Comment by gregpriday** [comment]
Yeah, very good idea. The new settings framework doesn't have support for conditionals yet, but I can take a look at adding those. Not sure on the best way of getting those working in the customizer.

For the header widget area, that's easy enough to hide when the user has logo in menu selected, but the widget area would only disappear on page reload.

**Comment by Misplon** [comment]
Cool. I have other conditional requests so I'm going to log that. If it's possible in an acceptable way in the Customizer then we can revisit this.

**Comment by Misplon** [comment]
Perhaps in the new settings framework in new themes - future.
