### ISSUE TITLE
Responsive Menu Collapse: Change setting to measurement

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#52]
It's really common for users to enter a value that's too low like say 10 and then not understand why the responsive menu doesn't work. This ideally needs to be a measurement setting with a minimum of 480. Ideally, users shouldn't be able to break the responsive menu by setting a value below 480.

**Comment by adiraomj** [comment]
_Update from Slack conversation:_ @Misplon and I decided to make this a range field.
