### ISSUE TITLE
Polylang Plugin: Add styling for the language switcher widget.

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#55]
The Polylang language switcher widget is most commonly used in the header widget area, we just need to remove the list style and make sure it looks normal. Let's also check it in the sidebar, footer and Page Builder.

@gregpriday Should we add this as an extra stylesheet dependent on Polylang being active? Should all plugin CSS be in conditional stylesheets? Or only when it's over x amount of lines?

**Comment by adiraomj** [comment]
@Misplon we moved the social widget's CSS to a new file as it has turned out to be quite large. Almost 600 lines :)

**Comment by gregpriday** [comment]
I think we need an x lines condition. Although if we start supporting a lot of niche widgets, we could also land up with a lot of unnecessary styling in the main stylesheet. We can make a decision if that happens, though.

**Comment by Misplon** [comment]
Cool, let's decide on x lines condition at some point in the future.
