### ISSUE TITLE
Update vantage_display_logo

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#56]
The function uses `jetpack_the_site_logo` which should be replaced with `the_custom_logo`. The custom logo feature has been moved from Jetpack to the core since WP 4.5.

We should also change the theme support to `add_theme_support( 'custom-logo' );`. This will allow us to use the feature even if jetpack is not installed.

Should I go ahead with this @gregpriday ?

**Comment by Misplon** [comment]
@adiraomj Nicely spotted. This is actually quite important because users previously using the Jetpack feature won't have a logo anymore. Please, proceed with this ASAP. If possible we should try include this in Monday's release.
