### ISSUE TITLE
Settings framework bugs

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#57]
Found a couple of issues.

The `measurement` field type does not show units in [customizer.php](https://github.com/siteorigin/vantage/blob/develop/inc/customizer.php).

The `text` fields in [settings.php](https://github.com/siteorigin/vantage/blob/develop/inc/settings.php) is showing an empty select field below the text input.

I am using the latest version of the settings submodule.

**Comment by gregpriday** [comment]
I'll get on these.

**Comment by gregpriday** [comment]
I've fixed the text field issue - I'll commit that now.

The other issue is actually just a limitation in the old customizer framework we're using in Vantage. It's not really a full measurement field like we have in the new settings framework. It's just a text field that appends a unit. The unit is specified in the settings array.
