### ISSUE TITLE
Create blank footer layout

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#6]
Certain users are messing up their sites because they can't work out how to do this. :crying_cat_face:

**Comment by gregpriday** [comment]
So to be clear, they just want to have a footer that essentially doesn't exist? Would it not be worth having a blank header template too? Unless we already have this, I can't remember at the moment.

**Comment by AlexGStapleton** [comment]
We have a masthead menu template that outputs an empty menu, but not one for the overall header.

The idea is that this (and an empty masthead) would allow for the user to use PB more as the "theme". This is obviously possible now with CSS but right now users have to ask for instructions on how to do this.

**Comment by gregpriday** [comment]
I like this idea. It would also be good to have them as page specific
settings too.

**Comment by Misplon** [comment]
@gregpriday Do you want to add page settings to remove the header and another page setting to remove the footer? I've also seen this use case. It's usually for landing pages or one page sites so page settings could work really nicely.

**Comment by gregpriday** [comment]
Yeah, this is the perfect case for Page Settings. I'll handle this because there are a few things we need to consider in terms of playing-nice with our old page templates.

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/pull/30
