### ISSUE TITLE
Customizer Theme Design General: Consider inserting a link underline setting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#65]
Consider adding a setting to General (with the link color settings) to remove the link underline styling. @gregpriday.

**Comment by Misplon** [comment]
@adiraomj You're free to add this when possible.

**Comment by adiraomj** [comment]
What do you think about removing https://github.com/siteorigin/vantage/blob/develop/less/widgets.less#L70-L72 to accomodate this setting.

**Comment by Misplon** [comment]
I'm ok with that. @gregpriday you cool?

**Comment by gregpriday** [comment]
If we removed that line, we'd be changing the design of user's sites slightly. I'm assuming the default for this setting would be to keep the link underlining. So when a user updates the links in their footer (inside `ul`s) would suddenly be underlined.

I say we keep that styling and only apply this new setting to `entry-content` and text widget content. Anything that was currently underlined.

**Comment by Misplon** [comment]
Cool.

**Comment by adiraomj** [comment]
Ok. Thanks. Only entry-content and text widget then.
