### ISSUE TITLE
Meta Slider: Consider providing a XML import of the demo slider

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#68]
@gregpriday Let's consider providing a XML import of the demo slider for users to get started quickly.

**Comment by gregpriday** [comment]
Is this something we could provide in the docs?

**Comment by Misplon** [comment]
It's where I'd suggest putting it.

**Comment by Misplon** [comment]
XML import doesn't seem to be working for me for Meta Slider. I'm going to provide links to the demo slider's assets in the docs. Users have asked for those in the past. It'll be something like, hey, if you want to experiment with our demo images, find them here.
