### ISSUE TITLE
WooCommerce: Consider moving WooCommerce styling to its own file.

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#69]
We could move all WooCommerce related styling to it's own file which loads only when the widget is active.

**Comment by AlexGStapleton** [comment]
I like this idea a lot. It's quite redundant to include it on every page.

**Comment by gregpriday** [comment]
Yeah, that's a very decent speed enhancement.

**Comment by adiraomj** [comment]
@gregpriday should we keep this file under the theme folder or in the css folder?

**Comment by gregpriday** [comment]
Let's go with the `css` folder.
