### ISSUE TITLE
Make the "homepage" template display the feature image similar to the default homepage slider

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#7]
It seems silly you can't replicate the look of the homepage elsewhere without the meta slider plugin. Either allow this for the homepage template (seeing as it's the closest), or create another one with the functionality.

**Comment by Misplon** [comment]
@AlexGStapleton The new theme settings framework is now in Vantage. Users can remove the masthead bottom margin, this means that they can add a full-width stretched row, remove the margin and  replicate the look of the default home page without Meta Slider. That gap was always the issue that needed Custom CSS. In addition, we're tackling the question of featured images in pages in https://github.com/siteorigin/vantage/issues/16 so I'll close this and I think we have the points raised in this issue covered. Thanks for the effort.
