### ISSUE TITLE
Vantage Social Media Widget: Tel field to accept URL

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#73]
@adiraomj Sorry for missing this. Please, can we make the `Tel` field a bit smarter, just like the email field? Can we make it accept a URL if one is entered and only prepend `tel` if a phone number is detected?

**Comment by gregpriday** [comment]
Assume that would mean just checking for a field with numbers dashes and a
plus? There must be a decent PHP phone number checking snippet out there.

**Comment by adiraomj** [comment]
What we can do is use PHP's `FILTER_VALIDATE_URL` to validate url. If it fails we can display `tel:`. What do you think?

**Comment by Misplon** [comment]
I'm cool with doing that way around. @gregpriday ?

**Comment by adiraomj** [comment]
@Misplon I just went through out code again. The logic does use `FILTER_VALIDATE_URL` to check for a url.

However for `FILTER_VALIDATE_URL` to return true, the url must use `http://` or `https://`.

So for example:
`https://siteorigin.com` - Passes
`https://siteorigin.com` - Passes
`siteorigin.com` - Fails

https://github.com/siteorigin/vantage/blob/develop/inc/widgets.php#L321

**Comment by Misplon** [comment]
@adiraomj My bad for not testing that. Cool, this is fine, let's leave it. Thanks man.
