### ISSUE TITLE
Mobile sticky menu behaviour is different to desktop behaviour

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#8]
Testing in iOS Chrome and Safari, the sticky menu in Vantage disappears on swipe and then reappears when stopped. User feedback suggests that users would prefer to see the same sticky menu behaviour that we have on desktop with the sticky menu being present always when activated.

**Comment by adiraomj** [comment]
I guess we also had a look at a [very similar issue](https://github.com/siteorigin/siteorigin-north/issues/126) with North yesterday.

Correct me if I am wrong, but it is my understanding that jQuery's `ScrollTop()` method does not work on iOS and Android devices when scrolled via touch. I'm looking at what we can do about it. Any ideas @gregpriday?

Would have been really easy if `position: sticky;` had more [browser support](http://caniuse.com/#feat=css-sticky). :)

**Comment by gregpriday** [comment]
Yeah, this is pretty much the same issue we started having with North. So I assume it has something to do with a change in mobile browsers.

This definitely wasn't always the case with Vantage, and the issue did seem to come out of nowhere with North. I don't have any ideas or suggestions on how to fix this at the moment, but it's something we can look into down the line.

**Comment by Misplon** [comment]
@adiraomj, @AlexGStapleton  has found some additional information on the browser changes that lead to this issue. I've asked him to update this issue/ticket so we can look into it further. Once he posts with those links and feedback, please, could you take another look for us. Thanks :)

**Comment by AlexGStapleton** [comment]
To me, It looks like the scroll position isn't being updated until release** as if you scroll without letting go things won't update until you release. Would something [like this work](http://www.devinrolsen.com/basic-jquery-touchmove-event-setup/)? 

(not the code itself, the [touchmove event](https://developer.mozilla.org/en-US/docs/Web/Events/touchmove))

** Although this may be intentional based on [this recent change](http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/). :(

**Comment by Misplon** [comment]
Great, thanks for the links. @adiraomj, could you perhaps, take another look at this for us? Alex dropped two links above that may be of help.

**Comment by Misplon** [comment]
@AlexGStapleton Trying to prioritise. If this isn't being raised often as an issue, let's close it. Let me know or just close if happy to do so. Thanks mate.

**Comment by AlexGStapleton** [comment]
I'm happy to do this at this time. Oddly, this rarely comes up anymore.
