### ISSUE TITLE
Testing theme with WP Test

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#81]
I am testing the theme with [WP Test](http://wptest.io/).

The styling for ordered and unordered lists is quite different, like so

![vantage-lists](https://cloud.githubusercontent.com/assets/3372029/15982954/7299d3ee-2fb5-11e6-8443-669b186194c1.png)

As you can see ordered lists have a margin to the left, whereas unordered lists do not. We should make the `left-margin` uniform for both.  How would you like to go?

**Comment by gregpriday** [comment]
Should we just remove the left margin for first level items in ordered lists? At least get it to match the unordered list left margin.

**Comment by adiraomj** [comment]
Yes. I'll do that.
