### ISSUE TITLE
Consider highlighting comment by post author

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/vantage#82]
We could add styling to highlight comments made by post authors. This could also be a theme setting.

**Comment by AlexGStapleton** [comment]
Really like this idea.

**Comment by Misplon** [comment]
Nice one! 

We could either go with an overall highlight OR we could consider something more subtle. In the past I've done things like put a little star icon next to the author's name when they comment.

What you thinking @adiraomj?

**Comment by adiraomj** [comment]
I feel overall highlight would be too pronounced. Here is a subtle idea.

![vantage-author-comment](https://cloud.githubusercontent.com/assets/3372029/15985033/d2c60a92-2ffd-11e6-9573-c86b5106accf.png)

We could also add a text field option for this. If left blank we do not display anything.

What do you think? @Misplon @gregpriday

**Comment by Misplon** [comment]
I'm keen for something exactly like that @adiraomj.

**Comment by gregpriday** [comment]
Nice and subtle. That looks great!
