### ISSUE TITLE
Home slider Customizer setting not working

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#91]
In develop branch the Home Page Slider setting is having no effect when switching between Demo Slider and None. (The page settings meta box at Pages > Home is working as expected.)

**Comment by Misplon** [comment]
@adiraomj Please, check this one out if you can. Thanks.

**Comment by gregpriday** [comment]
@Misplon this appears to be working for me. Are you still getting the issue in the latest develop?

**Comment by adiraomj** [comment]
I'm getting this issue too.

When the page settings metabox value is set to **None** everything works as expected.
When the page settings metabox value is set to **Demo Slider**, you cannot change it in the customizer.

**Comment by gregpriday** [comment]
Aaah, I just need to fix this for new settings then.

https://github.com/siteorigin/vantage/blob/develop/inc/settings.php#L354-L366

**Comment by Misplon** [comment]
Not sure if this was always the case for me. Latest pull of `development` is working if home page is displaying latest posts but it isn't working if I use the default (static) home page.

**Comment by Misplon** [comment]
Further testing. Right now it only doesn't work if I use the default home page. Working if I assign another static home page.
