### ISSUE TITLE
Home page icon setting isn't working

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#92]
Home page icon setting doesn't appear to be working from the Customizer.

**Comment by gregpriday** [comment]
Does it work after you publish the changes?

**Comment by Misplon** [comment]
Unfortunately, it doesn't appear after saving and publishing changes.

**Comment by adiraomj** [comment]
I just had a look at the code.

For this to work the home link should have a trailing slash. eg:
`https://siteorigin.com/` - Works
`https://siteorigin.com` - Will not work

https://github.com/siteorigin/vantage/blob/develop/inc/menu.php#L23

@gregpriday do you think we should change this? Or maybe improve to conditional statement to include both senarios?

**Comment by Misplon** [comment]
Ideally, it would accommodate both scenarios.
