### ISSUE TITLE
Theme Settings: Consider renaming responsive menu to mobile menu

### ISSUE THREAD

**Issue by Misplon** [siteorigin/vantage#96]
Consider renaming the following:

Responsive Menu
Responsive Menu Collapse
Responsive Menu Text
Responsive Menu Search

to

Mobile Menu
Mobile Menu Collapse
Mobile Menu Text
Mobile Menu Search

@gregpriday Keen? @adiraomj idea.

**Comment by gregpriday** [comment]
Yeah, I'm keen. Quick fix if you want to handle it @adiraomj?

**Comment by Misplon** [comment]
Rad, thanks guys. I'll update docs accordingly. We'll continue on with this label for new themes.
